binop_separator = "Back"
comment_width = 100
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
